# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import interview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_users', models.ManyToManyField(related_name='estimated_users', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемые пользователи')),
                ('eval_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluating_user', to=settings.AUTH_USER_MODEL, verbose_name='Оценивающий пользователь')),
            ],
            options={
                'verbose_name_plural': 'Оценивающие',
                'verbose_name': 'Оценивающий',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала опроса')),
                ('end_date', models.DateField(default=interview.models.add_week, verbose_name='Дата конца опроса')),
                ('users_to_eval', models.ManyToManyField(to='interview.Evaluating')),
            ],
            options={
                'verbose_name_plural': 'Опросы',
                'verbose_name': 'Опрос',
            },
        ),
    ]
