# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluating',
            name='already_estimated_users',
            field=models.ManyToManyField(related_name='already_estimated', to=settings.AUTH_USER_MODEL, verbose_name='Оцененые пользователи'),
        ),
    ]
