# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorientationmark',
            options={'verbose_name': 'Клиентоориентированность', 'verbose_name_plural': 'Клиентоориентированность'},
        ),
        migrations.AlterModelOptions(
            name='communicationmark',
            options={'verbose_name': 'Коммуникация', 'verbose_name_plural': 'Коммуникация'},
        ),
        migrations.AlterModelOptions(
            name='controlmark',
            options={'verbose_name': 'Управление', 'verbose_name_plural': 'Управление'},
        ),
        migrations.AlterModelOptions(
            name='efficiencymark',
            options={'verbose_name': 'Эффективность, качество работы', 'verbose_name_plural': 'Эффективность, качество работы'},
        ),
        migrations.AlterModelOptions(
            name='evolutionmark',
            options={'verbose_name': 'Ориентация на развитие', 'verbose_name_plural': 'Ориентация на развитие'},
        ),
        migrations.AlterModelOptions(
            name='leadershipmark',
            options={'verbose_name': 'Лидерство', 'verbose_name_plural': 'Лидерство'},
        ),
        migrations.AlterModelOptions(
            name='professionalismmark',
            options={'verbose_name': 'Профессионализм', 'verbose_name_plural': 'Профессионализм'},
        ),
        migrations.AlterModelOptions(
            name='teamworkmark',
            options={'verbose_name': 'Работа в команде', 'verbose_name_plural': 'Работа в команде'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'verbose_name': 'Веса', 'verbose_name_plural': 'Веса'},
        ),
    ]
