# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalismmark',
            old_name='work_interst',
            new_name='work_interest',
        ),
    ]
