# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20161226_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamworkMark',
            fields=[
                ('userinheritance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marks.UserInheritance')),
                ('loyalty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Преданность компании')),
                ('teamwork', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение работать в команде')),
                ('entry_speed', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Скорость вхождения в коллектив')),
                ('adoption_speed', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Скорость принятия нового члена коллектива')),
                ('general_rhythm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение работать в общем ритме')),
                ('emotions_control', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение управлять эмоциями, не проявлять личных симпатий и антипатий')),
                ('listen', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение принимать чужую точку зрения и признавать свои ошибки')),
                ('delegate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение делегировать полномочия')),
                ('objectives_lead', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение руководить  в зависимости от целей')),
                ('objectives_comply', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение подчиняться в зависимости от целей')),
                ('help', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Умение смирять личные амбиции и оказывать помощь коллегам')),
            ],
            bases=('marks.userinheritance',),
        ),
    ]
