# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_teamworkmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinheritance',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемый пользователь'),
        ),
    ]
